import { PegTypes } from "types/PegTypes";
// export const InitialGameBoardState = [
//   PegTypes.FilledSlot,
//   PegTypes.FilledSlot,
//   PegTypes.FilledSlot,

//   PegTypes.FilledSlot,
//   PegTypes.FilledSlot,
//   PegTypes.FilledSlot,

//   PegTypes.FilledSlot,
//   PegTypes.FilledSlot,
//   PegTypes.FilledSlot,
//   PegTypes.FilledSlot,
//   PegTypes.FilledSlot,
//   PegTypes.FilledSlot,
//   PegTypes.FilledSlot,

//   PegTypes.FilledSlot,
//   PegTypes.FilledSlot,
//   PegTypes.FilledSlot,
//   PegTypes.EmptySlot, // Main
//   PegTypes.FilledSlot,
//   PegTypes.FilledSlot,
//   PegTypes.FilledSlot,

//   PegTypes.FilledSlot,
//   PegTypes.FilledSlot,
//   PegTypes.FilledSlot,
//   PegTypes.FilledSlot,
//   PegTypes.FilledSlot,
//   PegTypes.FilledSlot,
//   PegTypes.FilledSlot,

//   PegTypes.FilledSlot,
//   PegTypes.FilledSlot,
//   PegTypes.FilledSlot,

//   PegTypes.FilledSlot,
//   PegTypes.FilledSlot,
//   PegTypes.FilledSlot,
// ];

export const InitGameBoardState2: number[][] = [
  [
    PegTypes.InvisiblePeg,
    PegTypes.InvisiblePeg,
    PegTypes.FilledSlot,
    PegTypes.FilledSlot,
    PegTypes.FilledSlot,
    PegTypes.InvisiblePeg,
    PegTypes.InvisiblePeg,
  ],
  [
    PegTypes.InvisiblePeg,
    PegTypes.InvisiblePeg,
    PegTypes.FilledSlot,
    PegTypes.FilledSlot,
    PegTypes.FilledSlot,
    PegTypes.InvisiblePeg,
    PegTypes.InvisiblePeg,
  ],
  [
    PegTypes.FilledSlot,
    PegTypes.FilledSlot,
    PegTypes.FilledSlot,
    PegTypes.FilledSlot,
    PegTypes.FilledSlot,
    PegTypes.FilledSlot,
    PegTypes.FilledSlot,
  ],
  [
    PegTypes.FilledSlot,
    PegTypes.FilledSlot,
    PegTypes.FilledSlot,
    PegTypes.EmptySlot,
    PegTypes.FilledSlot,
    PegTypes.FilledSlot,
    PegTypes.FilledSlot,
  ],
  [
    PegTypes.FilledSlot,
    PegTypes.FilledSlot,
    PegTypes.FilledSlot,
    PegTypes.FilledSlot,
    PegTypes.FilledSlot,
    PegTypes.FilledSlot,
    PegTypes.FilledSlot,
  ],
  [
    PegTypes.InvisiblePeg,
    PegTypes.InvisiblePeg,
    PegTypes.FilledSlot,
    PegTypes.FilledSlot,
    PegTypes.FilledSlot,
    PegTypes.InvisiblePeg,
    PegTypes.InvisiblePeg,
  ],
  [
    PegTypes.InvisiblePeg,
    PegTypes.InvisiblePeg,
    PegTypes.FilledSlot,
    PegTypes.FilledSlot,
    PegTypes.FilledSlot,
    PegTypes.InvisiblePeg,
    PegTypes.InvisiblePeg,
  ],
];
